CREATE DATABASE cerraduraBD;

USE cerraduraBD;

CREATE TABLE usuarios(
	nombre VARCHAR(50) NOT NULL,
	apellidos VARCHAR(50) NOT NULL,
	user VARCHAR(50) NOT NULL,
	pin VARCHAR(500) NOT NULL,
	uuidTarjeta VARCHAR(100) NOT NULL UNIQUE,
	date_subs TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	nomCerradura VARCHAR(50) NOT NULL UNIQUE,
	idCerradura VARCHAR(100) NOT NULL,
	email VARCHAR(50) NOT NULL,
	estado VARCHAR(50) NOT NULL DEFAULT 'on',
   preferencia VARCHAR(50) NOT NULL DEFAULT 'on'
);

CREATE TABLE administradores(
	id_user INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user VARCHAR (50) UNIQUE,
	password VARCHAR(500) UNIQUE
);

CREATE TABLE usuariosEliminados(
	id_user INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user VARCHAR (50) UNIQUE NOT NULL UNIQUE
);

CREATE TABLE usuariosModificados(
	id_user INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user VARCHAR (50) UNIQUE NOT NULL UNIQUE,
	idCerradura VARCHAR(100) NOT NULL,
	uuidTarjeta VARCHAR(100) NOT NULL UNIQUE,
	pin VARCHAR(500) NOT NULL,
	preferencia VARCHAR(50) NOT NULL DEFAULT 'on'
);